#!/usr/bin/env bash

FAVORITES=(
  "$HOME/dev/redis/Redis-Enterprise/cnm"
  "$HOME/dev/redis/Redis-Enterprise/cnm-go"
  "$HOME/dev/redis/Redis-Enterprise/rl-automation"
)

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(
      {
        printf '%s\n' "${FAVORITES[@]}"

        # 2) fd search results
        fd --type d --max-depth 2 --min-depth 1 . ~/dev
      } \
      | sed 's:/*$::' \
      | awk '!seen[$0]++' \
      | fzf
    )
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
