# Keep Powerlevel10k's palette aligned with ~/.config/appearance, which
# `appearance light|dark|toggle` writes. This is an overlay so it works with a
# p10k configuration generated by `p10k configure`.

_p10k_appearance() {
  local file=${APPEARANCE_STATE_FILE:-$HOME/.config/appearance} appearance=

  if [[ -r $file ]]; then
    appearance="$(<$file)"
    appearance=${appearance//[[:space:]]/}
  fi

  [[ $appearance == light ]] && print -r -- light || print -r -- dark
}

_p10k_sync_appearance() {
  local appearance
  appearance="$(_p10k_appearance)"
  [[ $appearance == $_P10K_APPEARANCE ]] && return

  typeset -g _P10K_APPEARANCE=$appearance

  if [[ $appearance == light ]]; then
    # The generated classic preset uses a dark segment background and a few
    # near-white foregrounds. These values retain the preset's contrast on a
    # light terminal background.
    typeset -g POWERLEVEL9K_BACKGROUND=255
    typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=0
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=240
  else
    typeset -g POWERLEVEL9K_BACKGROUND=236
    typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=255
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=248
  fi

  (( $+functions[p10k] )) && p10k reload
}

# Check before every prompt so an `appearance` switch made in another shell
# reaches this one: the next prompt redraws in the new palette.
precmd_functions+=(_p10k_sync_appearance)
_p10k_sync_appearance
